pipeline {
    agent any
    stages {
        stage ('Build') {
            steps {
                sh 'cd ws-app/'
                sh 'mvn -X clean package'
            }
        }
        stage ('Stop current service'){
            steps{
                sh 'curl -X POST localhost:8080/actuator/shutdown'
            }
        }
    }
}